import { cover } from "./homeData";
import type { Ebook } from "../types/ebook";

const recommended = (percent: number, reviewCount: number): Ebook["rating"] => ({
  percent,
  reviewCount,
  label: "Overwhelmingly recommended",
});

export const ebookList: Ebook[] = [
  {
    id: "1",
    slug: "rmji",
    title: "A Record of a Mortal's Journey to Immortality",
    author: "Wang Yu (忘语)",
    translator: "Johnchen & DoubleDD",
    price: 80,
    cover: cover("rmji"),
    rating: recommended(100, 3),
  },
  {
    id: "2",
    slug: "rmji-immortal-realm",
    title: "A Record of a Mortal's Journey to Immortality: Immortal Realm",
    author: "Wang Yu (忘语)",
    translator: "Johnchen",
    price: 50,
    cover: cover("rmji"),
    rating: recommended(100, 1),
  },
  {
    id: "3",
    slug: "a-will-eternal",
    title: "A Will Eternal",
    author: "Er Gen (耳根)",
    translator: "Deathblade",
    price: 40,
    cover: cover("a-will-eternal"),
    rating: recommended(100, 5),
  },
  {
    id: "4",
    slug: "above-your-head",
    title: "Above Your Head",
    author: "박건",
    translator: "GodSeth",
    price: 10,
    cover: cover("above-your-head"),
  },
  {
    id: "5",
    slug: "almighty-sword-domain",
    title: "Almighty Sword Domain",
    author: "On Azure Phoenix Peak (青鸾峰上)",
    translator: "InVader",
    price: 95,
    cover: cover("almighty-sword-domain"),
    rating: recommended(100, 1),
  },
  {
    id: "6",
    slug: "ancient-strengthening-technique",
    title: "Ancient Strengthening Technique",
    author: "I Eat Tomatoes (我吃西红柿)",
    translator: "RWX",
    price: 60,
    cover: cover("ast"),
    rating: recommended(100, 2),
  },
  {
    id: "7",
    slug: "battle-through-the-heavens",
    title: "Battle Through the Heavens",
    author: "Heavenly Silkworm Potato (天蚕土豆)",
    translator: "Gu Zhen Ren",
    price: 45,
    cover: cover("battle-through-the-heavens"),
    rating: recommended(100, 4),
  },
  {
    id: "8",
    slug: "coiling-dragon",
    title: "Coiling Dragon",
    author: "I Eat Tomatoes (我吃西红柿)",
    translator: "RWX",
    price: 55,
    cover: cover("coiling-dragon"),
    rating: recommended(100, 6),
  },
  {
    id: "9",
    slug: "desolate-era",
    title: "Desolate Era",
    author: "I Eat Tomatoes (我吃西红柿)",
    translator: "RWX",
    price: 70,
    cover: cover("desolate-era"),
    rating: recommended(100, 3),
  },
  {
    id: "10",
    slug: "i-shall-seal-the-heavens",
    title: "I Shall Seal the Heavens",
    author: "Er Gen (耳根)",
    translator: "Deathblade",
    price: 65,
    cover: cover("i-shall-seal-the-heavens"),
    rating: recommended(100, 8),
  },
  {
    id: "11",
    slug: "martial-world",
    title: "Martial World",
    author: "Cocooned Cow (蚕茧里的牛)",
    translator: "RWX",
    price: 75,
    cover: cover("martial-world"),
    rating: recommended(100, 2),
  },
  {
    id: "12",
    slug: "perfect-world",
    title: "Perfect World",
    author: "Chen Dong (辰东)",
    translator: "Pewpew",
    price: 50,
    cover: cover("perfect-world"),
  },
  {
    id: "13",
    slug: "renegade-immortal",
    title: "Renegade Immortal",
    author: "Er Gen (耳根)",
    translator: "RWX",
    price: 85,
    cover: cover("renegade-immortal"),
    rating: recommended(100, 7),
  },
  {
    id: "14",
    slug: "young-noble-be-monster-slaying",
    title: "Young Noble Be Monster Slaying",
    author: "Pei Bu Liao (装不了)",
    translator: "GLTD Alternate Universe",
    price: 35,
    cover: cover("young-noble-be-monster-slaying"),
  },
  {
    id: "15",
    slug: "yuans-ascension",
    title: "Yuan's Ascension",
    author: "Feng Xian (烽仙)",
    translator: "Whysee",
    price: 50,
    cover: cover("yuans-ascension"),
  },
];
