import type {
  Announcement,
  FeaturedSlide,
  FscSubscriptionOffer,
  GenreSeries,
  Novel,
  PromoBanner,
  RankedNovel,
  RecentUpdate,
  TrendingSidebarNovel,
} from "../types/novel";

const CDN = "https://cdn.wuxiaworld.com/covers";

export const cover = (slug: string) => `${CDN}/${slug}-250c.webp`;

export const featuredSlides: FeaturedSlide[] = [
  {
    id: 1,
    title: "Chosen: Beyond Fate",
    status: "Ongoing",
    approval: 100,
    description:
      "After the world destroyed itself, it was rebuilt. Upon perilous cliffs, towering cities rose once more.",
    cover: cover("chosen-beyond-fate"),
    banner: cover("chosen-beyond-fate"),
  },
  {
    id: 2,
    title: "Scripture of Days Past",
    status: "Ongoing",
    approval: 92,
    description:
      "A scholar stumbles upon an ancient scripture that rewrites the history of cultivation—and his own destiny along with it.",
    cover: cover("scripture-of-days-past"),
    banner: cover("scripture-of-days-past"),
  },
];

export const announcements: Announcement[] = [
  {
    id: 1,
    title: "Chosen: Beyond Fate, a post-apocalyptic a...",
    timeAgo: "7 days ago",
  },
  {
    id: 2,
    title: "Scripture of Days Past, a new fantasy ser...",
    timeAgo: "14 days ago",
  },
  {
    id: 3,
    title: "Destiny in Cinders reaches 100 chapters...",
    timeAgo: "a month ago",
  },
  {
    id: 4,
    title: "Dragon Canon translation quality updat...",
    timeAgo: "a month ago",
  },
];

export const promoBanners: PromoBanner[] = [
  {
    id: 1,
    title: "3 Must-Reads on Wuxiaworld",
    badge: "Staff Pick",
    cta: "See the Picks",
    comments: 48,
    gradient: "linear-gradient(135deg, #1e3a5f 0%, #2d5a87 50%, #1a2f4a 100%)",
  },
  {
    id: 2,
    title: "THE 3 WACKIEST MAIN CHARACTERS",
    comments: 37,
    gradient: "linear-gradient(135deg, #4a1942 0%, #7b2d8b 40%, #c44dff 100%)",
  },
];

export const popularThisWeek: Novel[] = [
  {
    id: 1,
    slug: "tribulation-of-myriad-clans",
    title: "Tribulation of Myriad Clans",
    author: "Wuxiaworld",
    cover: cover("tribulation-of-myriad-clans"),
    latestChapter: "Chapter 120",
    rating: 4.8,
    status: "Ongoing",
    approval: 88,
  },
  {
    id: 2,
    slug: "martial-god-asura",
    title: "Martial God Asura",
    author: "Kindhearted Bee",
    cover: cover("martial-god-asura"),
    latestChapter: "Chapter 5000",
    rating: 4.7,
    status: "Ongoing",
    approval: 85,
  },
  {
    id: 3,
    slug: "nine-star-hegemon-body-arts",
    title: "Nine Star Hegemon Body Art",
    author: "Mad Snail",
    cover: cover("nine-star-hegemon-body-arts"),
    latestChapter: "Chapter 4800",
    rating: 4.6,
    status: "Ongoing",
    approval: 69,
  },
  {
    id: 4,
    slug: "second-life-ranker",
    title: "Second Life Ranker",
    author: "Sadoyeon",
    cover: cover("second-life-ranker"),
    latestChapter: "Chapter 700",
    rating: 4.9,
    status: "Ongoing",
    approval: 91,
  },
  {
    id: 5,
    slug: "solo-leveling-ragnarok",
    title: "Solo Leveling: Ragnarok",
    author: "Chugong",
    cover: cover("solo-leveling-ragnarok"),
    latestChapter: "Chapter 50",
    rating: 4.5,
    status: "Completed",
    approval: 71,
  },
];

export const trendingRanked: RankedNovel[] = [
  {
    id: 1,
    rank: 1,
    slug: "nine-star-hegemon-body-arts",
    title: "Nine Star Hegemon Body Art",
    author: "Mad Snail",
    cover: cover("nine-star-hegemon-body-arts"),
    latestChapter: "Chapter 4800",
    rating: 4.6,
    approval: 69,
    status: "Ongoing",
  },
  {
    id: 2,
    rank: 2,
    slug: "martial-god-asura",
    title: "Martial God Asura",
    author: "Kindhearted Bee",
    cover: cover("martial-god-asura"),
    latestChapter: "Chapter 5000",
    rating: 4.7,
    approval: 80,
    status: "Ongoing",
  },
  {
    id: 3,
    rank: 3,
    slug: "second-life-ranker",
    title: "Second Life Ranker",
    author: "Sadoyeon",
    cover: cover("second-life-ranker"),
    latestChapter: "Chapter 700",
    rating: 4.9,
    approval: 75,
    status: "Ongoing",
  },
  {
    id: 4,
    rank: 4,
    slug: "tribulation-of-myriad-clans",
    title: "Tribulation of Myriad Clans",
    author: "Wuxiaworld",
    cover: cover("tribulation-of-myriad-clans"),
    latestChapter: "Chapter 120",
    rating: 4.8,
    approval: 72,
    status: "Ongoing",
  },
  {
    id: 5,
    rank: 5,
    slug: "solo-leveling-ragnarok",
    title: "Solo Leveling: Ragnarok",
    author: "Chugong",
    cover: cover("solo-leveling-ragnarok"),
    latestChapter: "Chapter 50",
    rating: 4.5,
    approval: 71,
    status: "Completed",
  },
];

export const newReleases: Novel[] = [
  {
    id: 1,
    slug: "chosen-beyond-fate",
    title: "Chosen: Beyond Fate",
    author: "Wey",
    cover: cover("chosen-beyond-fate"),
    latestChapter: "Chapter 30",
    rating: 4.9,
    status: "Ongoing",
  },
  {
    id: 2,
    slug: "scripture-of-days-past",
    title: "Scripture of Days Past",
    author: "Wuxiaworld",
    cover: cover("scripture-of-days-past"),
    latestChapter: "Chapter 45",
    rating: 4.7,
    status: "Ongoing",
  },
  {
    id: 3,
    slug: "destiny-in-cinders",
    title: "Destiny in Cinders",
    author: "Wuxiaworld",
    cover: cover("destiny-in-cinders"),
    latestChapter: "Chapter 100",
    rating: 4.6,
    status: "Ongoing",
  },
  {
    id: 4,
    slug: "dragon-canon",
    title: "Dragon Canon",
    author: "Wuxiaworld",
    cover: cover("dragon-canon"),
    latestChapter: "Chapter 60",
    rating: 4.5,
    status: "Ongoing",
  },
  {
    id: 5,
    slug: "13-mink-street",
    title: "13 Mink Street",
    author: "Wuxiaworld",
    cover: cover("13-mink-street"),
    latestChapter: "Chapter 20",
    rating: 4.4,
    status: "Ongoing",
  },
];

export const topSeriesByGenre: GenreSeries[] = [
  {
    id: 1,
    genre: "Cheat Systems",
    gradient: "linear-gradient(180deg, #2563eb 0%, #bfdbfe 50%, #e8e8e8 100%)",
    medal: "blue",
    novel: {
      id: 1,
      slug: "young-noble-be-monster-slaying",
      title: "Young Noble Be Monster Slaying",
      author: "Wuxiaworld",
      cover: cover("young-noble-be-monster-slaying"),
      latestChapter: "Chapter 200",
      rating: 4.8,
      status: "Completed",
      description:
        "In an imposing mortal world where the Divine Nine and Terrestrial Ten immortal...",
      approval: 91,
    },
  },
  {
    id: 2,
    genre: "Sci-fi",
    gradient: "linear-gradient(180deg, #0891b2 0%, #a5f3fc 50%, #e8e8e8 100%)",
    novel: {
      id: 2,
      slug: "hunter-of-immortals",
      title: "Hunter of Immortals",
      author: "Wuxiaworld",
      cover: cover("hunter-of-immortals"),
      latestChapter: "Chapter 120",
      rating: 4.5,
      status: "Completed",
      description:
        "\"The greatest equalizer in life is death. If it becomes possible to cheat death, equali...",
      approval: 62,
    },
  },
  {
    id: 3,
    genre: "Comedy",
    gradient: "linear-gradient(180deg, #16a34a 0%, #86efac 50%, #e8e8e8 100%)",
    novel: {
      id: 3,
      slug: "overlord-of-blood-and-iron",
      title: "Overlord of Blood and Iron",
      author: "Wuxiaworld",
      cover: cover("overlord-of-blood-and-iron"),
      latestChapter: "Chapter 300",
      rating: 4.4,
      status: "Completed",
      description:
        "Official Synopsis: Overlord Kang Chul-in. The man who lost only because he was...",
      approval: 57,
    },
  },
  {
    id: 4,
    genre: "LitRPG",
    gradient: "linear-gradient(180deg, #65a30d 0%, #d9f99d 50%, #e8e8e8 100%)",
    medal: "blue",
    novel: {
      id: 4,
      slug: "the-sorcerers-handbook",
      title: "The Sorcerer's Handbook",
      author: "Wuxiaworld",
      cover: cover("the-sorcerers-handbook"),
      latestChapter: "Chapter 90",
      rating: 4.6,
      status: "Completed",
      description:
        "In 1668, our city earned the title of \"The Safest Place in the Country.\" I had a lot t...",
      approval: 76,
    },
  },
];

export const genreTabs = [
  "Cheat Systems",
  "Comedy",
  "Mystery",
  "Fantasy",
  "Action",
  "Romance",
  "Sci-Fi",
  "Slice of Life",
] as const;

export const popularGenresNovels: Novel[] = [
  {
    id: 1,
    slug: "a-villains-will-to-survive",
    title: "A Villain's Will to Survive",
    author: "Wuxiaworld",
    cover: cover("a-villains-will-to-survive"),
    latestChapter: "Chapter 100",
    rating: 4.7,
    status: "Completed",
  },
  {
    id: 2,
    slug: "mythical-era-my-evolution-into-a",
    title: "Mythical Era: My Evolution into a...",
    author: "Wuxiaworld",
    cover: cover("mythical-era-my-evolution-into-a"),
    latestChapter: "Chapter 200",
    rating: 4.6,
    status: "Completed",
  },
  {
    id: 3,
    slug: "returning-to-the-mysterious-era",
    title: "Returning to the Mysterious Era",
    author: "Wuxiaworld",
    cover: cover("returning-to-the-mysterious-era"),
    latestChapter: "Chapter 150",
    rating: 4.8,
    status: "Completed",
  },
  {
    id: 4,
    slug: "second-life-ranker",
    title: "Second Life Ranker",
    author: "Sadoyeon",
    cover: cover("second-life-ranker"),
    latestChapter: "Chapter 700",
    rating: 4.9,
    status: "Ongoing",
  },
  {
    id: 5,
    slug: "solo-leveling-ragnarok",
    title: "Solo Leveling: Ragnarok",
    author: "Chugong",
    cover: cover("solo-leveling-ragnarok"),
    latestChapter: "Chapter 50",
    rating: 4.5,
    status: "Completed",
  },
];

export const recentlyUpdated: RecentUpdate[] = [
  {
    id: 1,
    seriesTitle: "Mirror World: Destined Return",
    chapterTitle: "Chapter 167",
    translator: "erigii",
    timeAgo: "2 hours ago",
    cover: cover("mirror-world-destined-return"),
  },
  {
    id: 2,
    seriesTitle: "The Last Place Hero's Return",
    chapterTitle: "Chapter 202: Traitors (3)",
    translator: "Nekogami",
    timeAgo: "27 minutes ago",
    cover: cover("the-last-place-heros-return"),
  },
  {
    id: 3,
    seriesTitle: "The Modern Martial Immortal",
    chapterTitle: "Chapter 180: Unrivaled",
    translator: "Joash",
    timeAgo: "27 minutes ago",
    cover: cover("the-modern-martial-immortal"),
  },
  {
    id: 4,
    seriesTitle: "The Modern Martial Immortal",
    chapterTitle: "Chapter 179: Spirit Gathering",
    translator: "Joash",
    timeAgo: "27 minutes ago",
    cover: cover("the-modern-martial-immortal"),
  },
];

export const loggedInPopularThisWeek: RankedNovel[] = [
  {
    id: 1,
    rank: 1,
    slug: "nine-star-hegemon-body-arts",
    title: "Nine Star Hegemon Body Art",
    author: "Mad Snail",
    cover: cover("nine-star-hegemon-body-arts"),
    latestChapter: "Chapter 4800",
    rating: 4.6,
    approval: 69,
    status: "Ongoing",
  },
  {
    id: 2,
    rank: 2,
    slug: "tribulation-of-myriad-clans",
    title: "Tribulation of Myriad Clans",
    author: "Wuxiaworld",
    cover: cover("tribulation-of-myriad-clans"),
    latestChapter: "Chapter 120",
    rating: 4.8,
    approval: 72,
    status: "Ongoing",
  },
  {
    id: 3,
    rank: 3,
    slug: "martial-god-asura",
    title: "Martial God Asura",
    author: "Kindhearted Bee",
    cover: cover("martial-god-asura"),
    latestChapter: "Chapter 5000",
    rating: 4.7,
    approval: 80,
    status: "Ongoing",
  },
  {
    id: 4,
    rank: 4,
    slug: "against-the-gods",
    title: "Against the Gods",
    author: "Yun Che",
    cover: cover("against-the-gods"),
    latestChapter: "Chapter 1900",
    rating: 4.5,
    approval: 74,
    status: "Ongoing",
  },
  {
    id: 5,
    rank: 5,
    slug: "emperors-domination",
    title: "Emperor's Domination",
    author: "Yan Er",
    cover: cover("emperors-domination"),
    latestChapter: "Chapter 4500",
    rating: 4.6,
    approval: 75,
    status: "Ongoing",
  },
];

export const trendingSidebarTabs = [
  "Fantasy",
  "Mystery",
  "Sci-fi",
  "Cultivation",
] as const;

export const trendingNovelsSidebar: TrendingSidebarNovel[] = [
  {
    id: 1,
    rank: 1,
    slug: "chosen-beyond-fate",
    title: "Chosen: Beyond Fate",
    author: "Wey",
    cover: cover("chosen-beyond-fate"),
    latestChapter: "Chapter 52",
    rating: 5,
    approval: 100,
    status: "Ongoing",
    chapterCount: 52,
  },
  {
    id: 2,
    rank: 2,
    slug: "global-awakening",
    title: "Global Awakening: I'm the Only One Ready",
    author: "Wuxiaworld",
    cover: cover("global-awakening"),
    latestChapter: "Chapter 318",
    rating: 4.2,
    approval: 57,
    status: "Ongoing",
    chapterCount: 318,
  },
  {
    id: 3,
    rank: 3,
    slug: "rookie-talent-agent",
    title: "Rookie Talent Agent Knows It All",
    author: "Wuxiaworld",
    cover: cover("rookie-talent-agent"),
    latestChapter: "Chapter 909",
    rating: 4.8,
    approval: 88,
    status: "Ongoing",
    chapterCount: 909,
  },
  {
    id: 4,
    rank: 4,
    slug: "descent-of-the-demon-master",
    title: "Descent of the Demon Master",
    author: "Wuxiaworld",
    cover: cover("descent-of-the-demon-master"),
    latestChapter: "Chapter 1464",
    rating: 4.5,
    approval: 68,
    status: "Ongoing",
    chapterCount: 1464,
  },
  {
    id: 5,
    rank: 5,
    slug: "star-gate",
    title: "Star Gate",
    author: "Wuxiaworld",
    cover: cover("star-gate"),
    latestChapter: "Chapter 1848",
    rating: 4.7,
    approval: 90,
    status: "Ongoing",
    chapterCount: 1848,
  },
];

export const fscSubscriptionSlides: FscSubscriptionOffer[][] = [
  [
    {
      id: 1,
      slug: "warlock-of-the-magus-world",
      title: "Warlock of the Magus World",
      cover: cover("warlock-of-the-magus-world"),
      status: "Completed",
      priceMonthly: "$8.99",
    },
    {
      id: 2,
      slug: "city-of-sin",
      title: "City of Sin",
      cover: cover("city-of-sin"),
      status: "Completed",
      priceMonthly: "$9.99",
    },
  ],
  [
    {
      id: 3,
      slug: "release-that-witch",
      title: "Release that Witch",
      cover: cover("release-that-witch"),
      status: "Completed",
      priceMonthly: "$8.99",
    },
    {
      id: 4,
      slug: "lord-of-all-realms",
      title: "Lord of All Realms",
      cover: cover("lord-of-all-realms"),
      status: "Completed",
      priceMonthly: "$9.99",
    },
  ],
];

export const footerLinks = {
  column1: ["About Us", "Contact Us"],
  column2: ["Announcements", "Jobs"],
  legal: ["Terms of Service", "Privacy Policy", "Cookie Policy"],
};
